export const data = {
  data: {
    id: 'network-424a75a9-9acb-44c8-a20c-9e83961e6aba',
    type: 'network',
    attributes: {
      nodes: [
        {
          id: 'en/pavement',
          name: 'pavement',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/litter',
          name: 'litter',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/fly',
          name: 'fly',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/trail',
          name: 'trail',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/include',
          name: 'include',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/waste',
          name: 'waste',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/increase',
          name: 'increase',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/market',
          name: 'market',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/good',
          name: 'good',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/diversity',
          name: 'diversity',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/wide',
          name: 'wide',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/reduce',
          name: 'reduce',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/age',
          name: 'age',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/set',
          name: 'set',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/street',
          name: 'street',
          val: 8.402595089184079,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/need',
          name: 'need',
          val: 6.738346384360904,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/road',
          name: 'road',
          val: 5.83234779752563,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/encourage',
          name: 'encourage',
          val: 4.867526116851975,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/support',
          name: 'support',
          val: 4.851665075850178,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/place',
          name: 'place',
          val: 4.141958919023704,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/woodgrange',
          name: 'woodgrange',
          val: 3.8813139812299755,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/business',
          name: 'business',
          val: 3.5460810475119353,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/food',
          name: 'food',
          val: 3.454384057398174,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/shop',
          name: 'shop',
          val: 3.2788134161773344,
          cluster_id: null,
          color_index: 0,
        },
        {
          id: 'en/people',
          name: 'people',
          val: 9.732502387716933,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/young',
          name: 'young',
          val: 6.157842912885945,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/child',
          name: 'child',
          val: 5.813495440054716,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/activity',
          name: 'activity',
          val: 5.168932446377051,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/health',
          name: 'health',
          val: 4.616746908333244,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/etc',
          name: 'etc',
          val: 4.486002857267371,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/mental',
          name: 'mental',
          val: 4.211891068766516,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/benefit',
          name: 'benefit',
          val: 3.506856409026126,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/social',
          name: 'social',
          val: 3.2629547474688767,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/outdoor',
          name: 'outdoor',
          val: 3.256117439500245,
          cluster_id: null,
          color_index: 1,
        },
        {
          id: 'en/help',
          name: 'help',
          val: 7.16748647724253,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/resident',
          name: 'resident',
          val: 6.444043855533467,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/newham',
          name: 'newham',
          val: 5.512975873609594,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/gate',
          name: 'gate',
          val: 4.893729498181948,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/youth',
          name: 'youth',
          val: 4.188000779364886,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/provide',
          name: 'provide',
          val: 3.9669271038523943,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/borough',
          name: 'borough',
          val: 3.8678255241920816,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/issue',
          name: 'issue',
          val: 3.3772674098532254,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/garden',
          name: 'garden',
          val: 3.273938827196356,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/year',
          name: 'year',
          val: 3.24448650204003,
          cluster_id: null,
          color_index: 2,
        },
        {
          id: 'en/community',
          name: 'community',
          val: 15.0,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/local',
          name: 'local',
          val: 11.927924628060369,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/project',
          name: 'project',
          val: 5.526907687716273,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/school',
          name: 'school',
          val: 4.4260749779620046,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/use',
          name: 'use',
          val: 4.166755794743496,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/group',
          name: 'group',
          val: 3.8736258275394553,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/great',
          name: 'great',
          val: 3.622653180799383,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/walk',
          name: 'walk',
          val: 3.073062360520785,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/way',
          name: 'way',
          val: 3.0283652639086394,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/centre',
          name: 'centre',
          val: 3.019080499524993,
          cluster_id: null,
          color_index: 3,
        },
        {
          id: 'en/space',
          name: 'space',
          val: 9.602623577506625,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/forest',
          name: 'forest',
          val: 9.10934662974201,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/park',
          name: 'park',
          val: 6.743569082596319,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/create',
          name: 'create',
          val: 4.831850817688384,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/green',
          name: 'green',
          val: 4.469045917897484,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/play',
          name: 'play',
          val: 4.157597159061016,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/safe',
          name: 'safe',
          val: 3.951294294902063,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/tree',
          name: 'tree',
          val: 3.9393084837001604,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/new',
          name: 'new',
          val: 3.777555335522518,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/plant',
          name: 'plant',
          val: 3.7544983068574576,
          cluster_id: null,
          color_index: 4,
        },
        {
          id: 'en/area',
          name: 'area',
          val: 8.870519316277738,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/improve',
          name: 'improve',
          val: 6.154701995957873,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/high',
          name: 'high',
          val: 5.6981138684088375,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/public',
          name: 'public',
          val: 4.519344615826258,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/environment',
          name: 'environment',
          val: 4.191041965797988,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/art',
          name: 'art',
          val: 4.054236456583181,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/work',
          name: 'work',
          val: 4.032330693575137,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/feel',
          name: 'feel',
          val: 3.4878030560267765,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/family',
          name: 'family',
          val: 3.135634994719413,
          cluster_id: null,
          color_index: 5,
        },
        {
          id: 'en/look',
          name: 'look',
          val: 3.0,
          cluster_id: null,
          color_index: 5,
        },
      ],
      links: [
        { source: 'en/community', target: 'en/space', weight: 15 },
        { source: 'en/community', target: 'en/green', weight: 7 },
        { source: 'en/community', target: 'en/garden', weight: 3 },
        { source: 'en/community', target: 'en/school', weight: 6 },
        { source: 'en/community', target: 'en/resident', weight: 8 },
        { source: 'en/community', target: 'en/centre', weight: 5 },
        { source: 'en/community', target: 'en/issue', weight: 1 },
        { source: 'en/community', target: 'en/forest', weight: 13 },
        { source: 'en/community', target: 'en/local', weight: 11 },
        { source: 'en/community', target: 'en/provide', weight: 6 },
        { source: 'en/community', target: 'en/young', weight: 1 },
        { source: 'en/community', target: 'en/support', weight: 6 },
        { source: 'en/community', target: 'en/create', weight: 6 },
        { source: 'en/community', target: 'en/encourage', weight: 4 },
        { source: 'en/community', target: 'en/mental', weight: 3 },
        { source: 'en/community', target: 'en/people', weight: 10 },
        { source: 'en/community', target: 'en/group', weight: 8 },
        { source: 'en/community', target: 'en/set', weight: 6 },
        { source: 'en/community', target: 'en/new', weight: 2 },
        { source: 'en/community', target: 'en/age', weight: 3 },
        { source: 'en/community', target: 'en/reduce', weight: 4 },
        { source: 'en/community', target: 'en/wide', weight: 4 },
        { source: 'en/community', target: 'en/play', weight: 6 },
        { source: 'en/community', target: 'en/project', weight: 6 },
        { source: 'en/community', target: 'en/borough', weight: 1 },
        { source: 'en/community', target: 'en/benefit', weight: 6 },
        { source: 'en/community', target: 'en/outdoor', weight: 2 },
        { source: 'en/community', target: 'en/business', weight: 2 },
        { source: 'en/community', target: 'en/great', weight: 7 },
        { source: 'en/community', target: 'en/use', weight: 3 },
        { source: 'en/community', target: 'en/woodgrange', weight: 4 },
        { source: 'en/community', target: 'en/area', weight: 9 },
        { source: 'en/community', target: 'en/social', weight: 1 },
        { source: 'en/community', target: 'en/need', weight: 5 },
        { source: 'en/community', target: 'en/safe', weight: 4 },
        { source: 'en/community', target: 'en/improve', weight: 5 },
        { source: 'en/community', target: 'en/place', weight: 6 },
        { source: 'en/community', target: 'en/child', weight: 2 },
        { source: 'en/community', target: 'en/help', weight: 6 },
        { source: 'en/community', target: 'en/health', weight: 2 },
        { source: 'en/community', target: 'en/feel', weight: 1 },
        { source: 'en/community', target: 'en/activity', weight: 3 },
        { source: 'en/community', target: 'en/gate', weight: 5 },
        { source: 'en/community', target: 'en/street', weight: 7 },
        { source: 'en/community', target: 'en/diversity', weight: 3 },
        { source: 'en/community', target: 'en/newham', weight: 3 },
        { source: 'en/community', target: 'en/park', weight: 6 },
        { source: 'en/community', target: 'en/art', weight: 3 },
        { source: 'en/community', target: 'en/public', weight: 1 },
        { source: 'en/community', target: 'en/walk', weight: 1 },
        { source: 'en/community', target: 'en/work', weight: 3 },
        { source: 'en/community', target: 'en/good', weight: 5 },
        { source: 'en/community', target: 'en/environment', weight: 1 },
        { source: 'en/community', target: 'en/market', weight: 5 },
        { source: 'en/community', target: 'en/youth', weight: 3 },
        { source: 'en/community', target: 'en/increase', weight: 3 },
        { source: 'en/community', target: 'en/high', weight: 1 },
        { source: 'en/community', target: 'en/waste', weight: 1 },
        { source: 'en/community', target: 'en/plant', weight: 1 },
        { source: 'en/community', target: 'en/family', weight: 6 },
        { source: 'en/community', target: 'en/food', weight: 1 },
        { source: 'en/community', target: 'en/way', weight: 3 },
        { source: 'en/community', target: 'en/include', weight: 3 },
        { source: 'en/local', target: 'en/people', weight: 6 },
        { source: 'en/local', target: 'en/business', weight: 2 },
        { source: 'en/local', target: 'en/resident', weight: 1 },
        { source: 'en/local', target: 'en/public', weight: 1 },
        { source: 'en/local', target: 'en/child', weight: 2 },
        { source: 'en/local', target: 'en/school', weight: 3 },
        { source: 'en/local', target: 'en/shop', weight: 6 },
        { source: 'en/local', target: 'en/food', weight: 3 },
        { source: 'en/local', target: 'en/area', weight: 4 },
        { source: 'en/local', target: 'en/street', weight: 8 },
        { source: 'en/local', target: 'en/park', weight: 9 },
        { source: 'en/local', target: 'en/art', weight: 1 },
        { source: 'en/local', target: 'en/group', weight: 7 },
        { source: 'en/local', target: 'en/environment', weight: 4 },
        { source: 'en/local', target: 'en/family', weight: 5 },
        { source: 'en/local', target: 'en/activity', weight: 3 },
        { source: 'en/local', target: 'en/feel', weight: 3 },
        { source: 'en/local', target: 'en/market', weight: 4 },
        { source: 'en/local', target: 'en/walk', weight: 4 },
        { source: 'en/local', target: 'en/borough', weight: 2 },
        { source: 'en/local', target: 'en/waste', weight: 2 },
        { source: 'en/local', target: 'en/look', weight: 3 },
        { source: 'en/local', target: 'en/use', weight: 7 },
        { source: 'en/local', target: 'en/support', weight: 6 },
        { source: 'en/local', target: 'en/create', weight: 5 },
        { source: 'en/local', target: 'en/encourage', weight: 6 },
        { source: 'en/local', target: 'en/set', weight: 4 },
        { source: 'en/local', target: 'en/tree', weight: 1 },
        { source: 'en/local', target: 'en/improve', weight: 9 },
        { source: 'en/local', target: 'en/place', weight: 2 },
        { source: 'en/local', target: 'en/increase', weight: 2 },
        { source: 'en/local', target: 'en/need', weight: 1 },
        { source: 'en/local', target: 'en/year', weight: 1 },
        { source: 'en/local', target: 'en/help', weight: 5 },
        { source: 'en/local', target: 'en/road', weight: 1 },
        { source: 'en/local', target: 'en/plant', weight: 1 },
        { source: 'en/local', target: 'en/high', weight: 3 },
        { source: 'en/local', target: 'en/benefit', weight: 6 },
        { source: 'en/local', target: 'en/centre', weight: 2 },
        { source: 'en/local', target: 'en/safe', weight: 1 },
        { source: 'en/local', target: 'en/green', weight: 3 },
        { source: 'en/local', target: 'en/include', weight: 4 },
        { source: 'en/local', target: 'en/wide', weight: 2 },
        { source: 'en/local', target: 'en/space', weight: 8 },
        { source: 'en/local', target: 'en/forest', weight: 1 },
        { source: 'en/local', target: 'en/gate', weight: 6 },
        { source: 'en/local', target: 'en/newham', weight: 2 },
        { source: 'en/local', target: 'en/project', weight: 19 },
        { source: 'en/local', target: 'en/health', weight: 5 },
        { source: 'en/local', target: 'en/trail', weight: 2 },
        { source: 'en/local', target: 'en/provide', weight: 3 },
        { source: 'en/local', target: 'en/garden', weight: 2 },
        { source: 'en/local', target: 'en/young', weight: 1 },
        { source: 'en/local', target: 'en/pavement', weight: 1 },
        { source: 'en/local', target: 'en/great', weight: 3 },
        { source: 'en/local', target: 'en/new', weight: 1 },
        { source: 'en/local', target: 'en/mental', weight: 2 },
        { source: 'en/local', target: 'en/work', weight: 5 },
        { source: 'en/local', target: 'en/way', weight: 3 },
        { source: 'en/local', target: 'en/diversity', weight: 3 },
        { source: 'en/local', target: 'en/good', weight: 4 },
        { source: 'en/group', target: 'en/encourage', weight: 2 },
        { source: 'en/group', target: 'en/create', weight: 6 },
        { source: 'en/group', target: 'en/green', weight: 3 },
        { source: 'en/group', target: 'en/help', weight: 1 },
        { source: 'en/group', target: 'en/provide', weight: 3 },
        { source: 'en/group', target: 'en/project', weight: 2 },
        { source: 'en/group', target: 'en/support', weight: 3 },
        { source: 'en/group', target: 'en/child', weight: 1 },
        { source: 'en/group', target: 'en/walk', weight: 3 },
        { source: 'en/group', target: 'en/social', weight: 4 },
        { source: 'en/group', target: 'en/resident', weight: 3 },
        { source: 'en/group', target: 'en/forest', weight: 2 },
        { source: 'en/group', target: 'en/gate', weight: 1 },
        { source: 'en/group', target: 'en/street', weight: 2 },
        { source: 'en/group', target: 'en/play', weight: 3 },
        { source: 'en/group', target: 'en/newham', weight: 3 },
        { source: 'en/group', target: 'en/young', weight: 2 },
        { source: 'en/group', target: 'en/public', weight: 1 },
        { source: 'en/group', target: 'en/space', weight: 4 },
        { source: 'en/group', target: 'en/safe', weight: 1 },
        { source: 'en/group', target: 'en/wide', weight: 1 },
        { source: 'en/group', target: 'en/school', weight: 3 },
        { source: 'en/group', target: 'en/art', weight: 3 },
        { source: 'en/group', target: 'en/age', weight: 3 },
        { source: 'en/group', target: 'en/good', weight: 1 },
        { source: 'en/encourage', target: 'en/people', weight: 3 },
        { source: 'en/encourage', target: 'en/shop', weight: 3 },
        { source: 'en/encourage', target: 'en/newham', weight: 5 },
        { source: 'en/encourage', target: 'en/child', weight: 3 },
        { source: 'en/encourage', target: 'en/use', weight: 3 },
        { source: 'en/encourage', target: 'en/resident', weight: 3 },
        { source: 'en/encourage', target: 'en/safe', weight: 1 },
        { source: 'en/encourage', target: 'en/support', weight: 3 },
        { source: 'en/encourage', target: 'en/area', weight: 5 },
        { source: 'en/encourage', target: 'en/young', weight: 2 },
        { source: 'en/encourage', target: 'en/feel', weight: 1 },
        { source: 'en/encourage', target: 'en/include', weight: 2 },
        { source: 'en/encourage', target: 'en/public', weight: 1 },
        { source: 'en/encourage', target: 'en/business', weight: 3 },
        { source: 'en/encourage', target: 'en/create', weight: 2 },
        { source: 'en/encourage', target: 'en/garden', weight: 2 },
        { source: 'en/encourage', target: 'en/benefit', weight: 1 },
        { source: 'en/encourage', target: 'en/street', weight: 7 },
        { source: 'en/encourage', target: 'en/increase', weight: 2 },
        { source: 'en/encourage', target: 'en/litter', weight: 3 },
        { source: 'en/encourage', target: 'en/new', weight: 2 },
        { source: 'en/encourage', target: 'en/space', weight: 5 },
        { source: 'en/encourage', target: 'en/way', weight: 2 },
        { source: 'en/encourage', target: 'en/project', weight: 3 },
        { source: 'en/encourage', target: 'en/road', weight: 2 },
        { source: 'en/encourage', target: 'en/park', weight: 5 },
        { source: 'en/encourage', target: 'en/need', weight: 1 },
        { source: 'en/encourage', target: 'en/high', weight: 1 },
        { source: 'en/encourage', target: 'en/activity', weight: 3 },
        { source: 'en/encourage', target: 'en/gate', weight: 1 },
        { source: 'en/encourage', target: 'en/improve', weight: 2 },
        { source: 'en/encourage', target: 'en/reduce', weight: 2 },
        { source: 'en/encourage', target: 'en/health', weight: 1 },
        { source: 'en/encourage', target: 'en/help', weight: 3 },
        { source: 'en/encourage', target: 'en/play', weight: 2 },
        { source: 'en/encourage', target: 'en/diversity', weight: 3 },
        { source: 'en/space', target: 'en/street', weight: 4 },
        { source: 'en/space', target: 'en/green', weight: 15 },
        { source: 'en/space', target: 'en/public', weight: 5 },
        { source: 'en/space', target: 'en/tree', weight: 9 },
        { source: 'en/space', target: 'en/help', weight: 3 },
        { source: 'en/space', target: 'en/young', weight: 12 },
        { source: 'en/space', target: 'en/child', weight: 1 },
        { source: 'en/space', target: 'en/new', weight: 9 },
        { source: 'en/space', target: 'en/school', weight: 3 },
        { source: 'en/space', target: 'en/create', weight: 9 },
        { source: 'en/space', target: 'en/resident', weight: 7 },
        { source: 'en/space', target: 'en/project', weight: 1 },
        { source: 'en/space', target: 'en/centre', weight: 1 },
        { source: 'en/space', target: 'en/shop', weight: 4 },
        { source: 'en/space', target: 'en/feel', weight: 3 },
        { source: 'en/space', target: 'en/outdoor', weight: 4 },
        { source: 'en/space', target: 'en/high', weight: 5 },
        { source: 'en/space', target: 'en/need', weight: 4 },
        { source: 'en/space', target: 'en/forest', weight: 6 },
        { source: 'en/space', target: 'en/borough', weight: 3 },
        { source: 'en/space', target: 'en/market', weight: 3 },
        { source: 'en/space', target: 'en/use', weight: 2 },
        { source: 'en/space', target: 'en/benefit', weight: 2 },
        { source: 'en/space', target: 'en/people', weight: 4 },
        { source: 'en/space', target: 'en/activity', weight: 6 },
        { source: 'en/space', target: 'en/garden', weight: 5 },
        { source: 'en/space', target: 'en/safe', weight: 8 },
        { source: 'en/space', target: 'en/look', weight: 1 },
        { source: 'en/space', target: 'en/plant', weight: 2 },
        { source: 'en/space', target: 'en/work', weight: 2 },
        { source: 'en/space', target: 'en/woodgrange', weight: 1 },
        { source: 'en/space', target: 'en/waste', weight: 1 },
        { source: 'en/space', target: 'en/road', weight: 3 },
        { source: 'en/space', target: 'en/improve', weight: 15 },
        { source: 'en/space', target: 'en/area', weight: 5 },
        { source: 'en/space', target: 'en/gate', weight: 4 },
        { source: 'en/space', target: 'en/way', weight: 1 },
        { source: 'en/space', target: 'en/park', weight: 10 },
        { source: 'en/space', target: 'en/wide', weight: 3 },
        { source: 'en/space', target: 'en/fly', weight: 2 },
        { source: 'en/space', target: 'en/environment', weight: 1 },
        { source: 'en/space', target: 'en/youth', weight: 1 },
        { source: 'en/space', target: 'en/art', weight: 2 },
        { source: 'en/space', target: 'en/increase', weight: 2 },
        { source: 'en/space', target: 'en/support', weight: 3 },
        { source: 'en/space', target: 'en/mental', weight: 2 },
        { source: 'en/space', target: 'en/good', weight: 2 },
        { source: 'en/space', target: 'en/play', weight: 5 },
        { source: 'en/space', target: 'en/family', weight: 2 },
        { source: 'en/space', target: 'en/set', weight: 2 },
        { source: 'en/space', target: 'en/age', weight: 2 },
        { source: 'en/space', target: 'en/newham', weight: 1 },
        { source: 'en/space', target: 'en/social', weight: 3 },
        { source: 'en/space', target: 'en/place', weight: 1 },
        { source: 'en/space', target: 'en/walk', weight: 1 },
        { source: 'en/space', target: 'en/health', weight: 1 },
        { source: 'en/space', target: 'en/provide', weight: 2 },
        { source: 'en/space', target: 'en/etc', weight: 3 },
        { source: 'en/space', target: 'en/great', weight: 3 },
        { source: 'en/space', target: 'en/year', weight: 3 },
        { source: 'en/space', target: 'en/diversity', weight: 1 },
        { source: 'en/space', target: 'en/include', weight: 1 },
        { source: 'en/create', target: 'en/safe', weight: 3 },
        { source: 'en/create', target: 'en/new', weight: 4 },
        { source: 'en/create', target: 'en/centre', weight: 3 },
        { source: 'en/create', target: 'en/need', weight: 3 },
        { source: 'en/create', target: 'en/high', weight: 1 },
        { source: 'en/create', target: 'en/place', weight: 4 },
        { source: 'en/create', target: 'en/art', weight: 2 },
        { source: 'en/create', target: 'en/young', weight: 1 },
        { source: 'en/create', target: 'en/environment', weight: 1 },
        { source: 'en/create', target: 'en/green', weight: 2 },
        { source: 'en/create', target: 'en/street', weight: 3 },
        { source: 'en/create', target: 'en/child', weight: 1 },
        { source: 'en/create', target: 'en/play', weight: 1 },
        { source: 'en/create', target: 'en/help', weight: 2 },
        { source: 'en/create', target: 'en/improve', weight: 1 },
        { source: 'en/create', target: 'en/market', weight: 2 },
        { source: 'en/create', target: 'en/plant', weight: 3 },
        { source: 'en/create', target: 'en/outdoor', weight: 2 },
        { source: 'en/create', target: 'en/borough', weight: 1 },
        { source: 'en/create', target: 'en/road', weight: 2 },
        { source: 'en/create', target: 'en/garden', weight: 2 },
        { source: 'en/create', target: 'en/people', weight: 4 },
        { source: 'en/create', target: 'en/newham', weight: 2 },
        { source: 'en/create', target: 'en/project', weight: 3 },
        { source: 'en/create', target: 'en/waste', weight: 3 },
        { source: 'en/create', target: 'en/reduce', weight: 2 },
        { source: 'en/create', target: 'en/business', weight: 3 },
        { source: 'en/create', target: 'en/tree', weight: 2 },
        { source: 'en/create', target: 'en/pavement', weight: 3 },
        { source: 'en/create', target: 'en/year', weight: 2 },
        { source: 'en/create', target: 'en/woodgrange', weight: 1 },
        { source: 'en/create', target: 'en/work', weight: 1 },
        { source: 'en/create', target: 'en/food', weight: 2 },
        { source: 'en/create', target: 'en/diversity', weight: 3 },
        { source: 'en/support', target: 'en/place', weight: 3 },
        { source: 'en/support', target: 'en/people', weight: 5 },
        { source: 'en/support', target: 'en/mental', weight: 5 },
        { source: 'en/support', target: 'en/street', weight: 4 },
        { source: 'en/support', target: 'en/set', weight: 2 },
        { source: 'en/support', target: 'en/young', weight: 3 },
        { source: 'en/support', target: 'en/forest', weight: 2 },
        { source: 'en/support', target: 'en/help', weight: 4 },
        { source: 'en/support', target: 'en/market', weight: 3 },
        { source: 'en/support', target: 'en/feel', weight: 2 },
        { source: 'en/support', target: 'en/resident', weight: 4 },
        { source: 'en/support', target: 'en/project', weight: 3 },
        { source: 'en/support', target: 'en/woodgrange', weight: 2 },
        { source: 'en/support', target: 'en/high', weight: 2 },
        { source: 'en/support', target: 'en/food', weight: 5 },
        { source: 'en/support', target: 'en/business', weight: 5 },
        { source: 'en/support', target: 'en/year', weight: 1 },
        { source: 'en/support', target: 'en/health', weight: 1 },
        { source: 'en/support', target: 'en/child', weight: 2 },
        { source: 'en/support', target: 'en/gate', weight: 3 },
        { source: 'en/support', target: 'en/play', weight: 2 },
        { source: 'en/support', target: 'en/work', weight: 1 },
        { source: 'en/support', target: 'en/garden', weight: 2 },
        { source: 'en/support', target: 'en/trail', weight: 1 },
        { source: 'en/support', target: 'en/shop', weight: 1 },
        { source: 'en/support', target: 'en/school', weight: 2 },
        { source: 'en/support', target: 'en/benefit', weight: 1 },
        { source: 'en/support', target: 'en/park', weight: 1 },
        { source: 'en/support', target: 'en/increase', weight: 3 },
        { source: 'en/support', target: 'en/need', weight: 3 },
        { source: 'en/support', target: 'en/activity', weight: 3 },
        { source: 'en/support', target: 'en/provide', weight: 4 },
        { source: 'en/support', target: 'en/plant', weight: 3 },
        { source: 'en/support', target: 'en/family', weight: 2 },
        { source: 'en/support', target: 'en/art', weight: 1 },
        { source: 'en/road', target: 'en/park', weight: 3 },
        { source: 'en/road', target: 'en/increase', weight: 3 },
        { source: 'en/road', target: 'en/trail', weight: 4 },
        { source: 'en/road', target: 'en/woodgrange', weight: 4 },
        { source: 'en/road', target: 'en/look', weight: 3 },
        { source: 'en/road', target: 'en/family', weight: 3 },
        { source: 'en/road', target: 'en/help', weight: 3 },
        { source: 'en/road', target: 'en/pavement', weight: 2 },
        { source: 'en/road', target: 'en/wide', weight: 3 },
        { source: 'en/road', target: 'en/high', weight: 1 },
        { source: 'en/road', target: 'en/social', weight: 1 },
        { source: 'en/road', target: 'en/project', weight: 2 },
        { source: 'en/road', target: 'en/need', weight: 4 },
        { source: 'en/road', target: 'en/garden', weight: 1 },
        { source: 'en/road', target: 'en/year', weight: 1 },
        { source: 'en/road', target: 'en/forest', weight: 1 },
        { source: 'en/road', target: 'en/waste', weight: 1 },
        { source: 'en/road', target: 'en/market', weight: 2 },
        { source: 'en/road', target: 'en/safe', weight: 1 },
        { source: 'en/road', target: 'en/gate', weight: 4 },
        { source: 'en/road', target: 'en/street', weight: 1 },
        { source: 'en/road', target: 'en/school', weight: 2 },
        { source: 'en/road', target: 'en/litter', weight: 3 },
        { source: 'en/road', target: 'en/newham', weight: 2 },
        { source: 'en/road', target: 'en/food', weight: 1 },
        { source: 'en/road', target: 'en/way', weight: 2 },
        { source: 'en/road', target: 'en/good', weight: 2 },
        { source: 'en/park', target: 'en/increase', weight: 1 },
        { source: 'en/park', target: 'en/gate', weight: 4 },
        { source: 'en/park', target: 'en/great', weight: 3 },
        { source: 'en/park', target: 'en/street', weight: 9 },
        { source: 'en/park', target: 'en/pavement', weight: 3 },
        { source: 'en/park', target: 'en/borough', weight: 4 },
        { source: 'en/park', target: 'en/look', weight: 1 },
        { source: 'en/park', target: 'en/green', weight: 6 },
        { source: 'en/park', target: 'en/area', weight: 2 },
        { source: 'en/park', target: 'en/improve', weight: 6 },
        { source: 'en/park', target: 'en/reduce', weight: 3 },
        { source: 'en/park', target: 'en/family', weight: 3 },
        { source: 'en/park', target: 'en/outdoor', weight: 2 },
        { source: 'en/park', target: 'en/social', weight: 3 },
        { source: 'en/park', target: 'en/need', weight: 1 },
        { source: 'en/park', target: 'en/forest', weight: 17 },
        { source: 'en/park', target: 'en/child', weight: 2 },
        { source: 'en/park', target: 'en/project', weight: 2 },
        { source: 'en/park', target: 'en/use', weight: 5 },
        { source: 'en/park', target: 'en/provide', weight: 3 },
        { source: 'en/park', target: 'en/play', weight: 2 },
        { source: 'en/park', target: 'en/safe', weight: 4 },
        { source: 'en/park', target: 'en/help', weight: 2 },
        { source: 'en/park', target: 'en/newham', weight: 1 },
        { source: 'en/park', target: 'en/way', weight: 1 },
        { source: 'en/park', target: 'en/young', weight: 1 },
        { source: 'en/park', target: 'en/public', weight: 1 },
        { source: 'en/park', target: 'en/health', weight: 1 },
        { source: 'en/park', target: 'en/high', weight: 2 },
        { source: 'en/park', target: 'en/litter', weight: 3 },
        { source: 'en/park', target: 'en/people', weight: 1 },
        { source: 'en/park', target: 'en/resident', weight: 2 },
        { source: 'en/park', target: 'en/waste', weight: 3 },
        { source: 'en/park', target: 'en/walk', weight: 3 },
        { source: 'en/park', target: 'en/garden', weight: 5 },
        { source: 'en/park', target: 'en/environment', weight: 2 },
        { source: 'en/park', target: 'en/etc', weight: 3 },
        { source: 'en/park', target: 'en/centre', weight: 1 },
        { source: 'en/park', target: 'en/mental', weight: 1 },
        { source: 'en/park', target: 'en/benefit', weight: 2 },
        { source: 'en/social', target: 'en/activity', weight: 5 },
        { source: 'en/social', target: 'en/mental', weight: 3 },
        { source: 'en/social', target: 'en/area', weight: 2 },
        { source: 'en/social', target: 'en/increase', weight: 3 },
        { source: 'en/social', target: 'en/diversity', weight: 1 },
        { source: 'en/social', target: 'en/high', weight: 1 },
        { source: 'en/social', target: 'en/people', weight: 3 },
        { source: 'en/social', target: 'en/art', weight: 3 },
        { source: 'en/social', target: 'en/help', weight: 2 },
        { source: 'en/social', target: 'en/youth', weight: 1 },
        { source: 'en/social', target: 'en/feel', weight: 2 },
        { source: 'en/social', target: 'en/forest', weight: 2 },
        { source: 'en/social', target: 'en/gate', weight: 3 },
        { source: 'en/social', target: 'en/improve', weight: 4 },
        { source: 'en/social', target: 'en/public', weight: 1 },
        { source: 'en/social', target: 'en/walk', weight: 2 },
        { source: 'en/social', target: 'en/reduce', weight: 3 },
        { source: 'en/social', target: 'en/fly', weight: 1 },
        { source: 'en/social', target: 'en/garden', weight: 3 },
        { source: 'en/social', target: 'en/use', weight: 1 },
        { source: 'en/social', target: 'en/age', weight: 3 },
        { source: 'en/social', target: 'en/outdoor', weight: 2 },
        { source: 'en/increase', target: 'en/use', weight: 3 },
        { source: 'en/increase', target: 'en/youth', weight: 3 },
        { source: 'en/increase', target: 'en/activity', weight: 3 },
        { source: 'en/increase', target: 'en/area', weight: 4 },
        { source: 'en/increase', target: 'en/diversity', weight: 5 },
        { source: 'en/increase', target: 'en/project', weight: 2 },
        { source: 'en/increase', target: 'en/help', weight: 4 },
        { source: 'en/increase', target: 'en/child', weight: 2 },
        { source: 'en/increase', target: 'en/young', weight: 1 },
        { source: 'en/increase', target: 'en/people', weight: 2 },
        { source: 'en/increase', target: 'en/business', weight: 3 },
        { source: 'en/increase', target: 'en/reduce', weight: 1 },
        { source: 'en/increase', target: 'en/improve', weight: 2 },
        { source: 'en/increase', target: 'en/shop', weight: 2 },
        { source: 'en/increase', target: 'en/borough', weight: 2 },
        { source: 'en/increase', target: 'en/street', weight: 2 },
        { source: 'en/increase', target: 'en/gate', weight: 1 },
        { source: 'en/increase', target: 'en/green', weight: 2 },
        { source: 'en/increase', target: 'en/waste', weight: 3 },
        { source: 'en/increase', target: 'en/feel', weight: 1 },
        { source: 'en/increase', target: 'en/trail', weight: 4 },
        { source: 'en/increase', target: 'en/garden', weight: 1 },
        { source: 'en/increase', target: 'en/tree', weight: 1 },
        { source: 'en/increase', target: 'en/pavement', weight: 1 },
        { source: 'en/increase', target: 'en/food', weight: 1 },
        { source: 'en/need', target: 'en/safe', weight: 1 },
        { source: 'en/need', target: 'en/provide', weight: 3 },
        { source: 'en/need', target: 'en/year', weight: 3 },
        { source: 'en/need', target: 'en/area', weight: 3 },
        { source: 'en/need', target: 'en/activity', weight: 4 },
        { source: 'en/need', target: 'en/feel', weight: 3 },
        { source: 'en/need', target: 'en/look', weight: 2 },
        { source: 'en/need', target: 'en/child', weight: 2 },
        { source: 'en/need', target: 'en/young', weight: 8 },
        { source: 'en/need', target: 'en/help', weight: 8 },
        { source: 'en/need', target: 'en/resident', weight: 1 },
        { source: 'en/need', target: 'en/improve', weight: 4 },
        { source: 'en/need', target: 'en/work', weight: 1 },
        { source: 'en/need', target: 'en/new', weight: 3 },
        { source: 'en/need', target: 'en/high', weight: 2 },
        { source: 'en/need', target: 'en/street', weight: 15 },
        { source: 'en/need', target: 'en/litter', weight: 2 },
        { source: 'en/need', target: 'en/youth', weight: 4 },
        { source: 'en/need', target: 'en/mental', weight: 1 },
        { source: 'en/need', target: 'en/shop', weight: 5 },
        { source: 'en/need', target: 'en/gate', weight: 3 },
        { source: 'en/need', target: 'en/use', weight: 1 },
        { source: 'en/need', target: 'en/walk', weight: 1 },
        { source: 'en/need', target: 'en/forest', weight: 2 },
        { source: 'en/need', target: 'en/people', weight: 4 },
        { source: 'en/need', target: 'en/newham', weight: 3 },
        { source: 'en/need', target: 'en/public', weight: 1 },
        { source: 'en/need', target: 'en/fly', weight: 1 },
        { source: 'en/need', target: 'en/health', weight: 4 },
        { source: 'en/need', target: 'en/business', weight: 3 },
        { source: 'en/need', target: 'en/plant', weight: 4 },
        { source: 'en/need', target: 'en/garden', weight: 1 },
        { source: 'en/need', target: 'en/etc', weight: 3 },
        { source: 'en/need', target: 'en/family', weight: 3 },
        { source: 'en/need', target: 'en/tree', weight: 1 },
        { source: 'en/need', target: 'en/pavement', weight: 3 },
        { source: 'en/need', target: 'en/centre', weight: 2 },
        { source: 'en/need', target: 'en/great', weight: 2 },
        { source: 'en/need', target: 'en/outdoor', weight: 1 },
        { source: 'en/high', target: 'en/street', weight: 5 },
        { source: 'en/high', target: 'en/shop', weight: 2 },
        { source: 'en/high', target: 'en/area', weight: 2 },
        { source: 'en/high', target: 'en/child', weight: 1 },
        { source: 'en/high', target: 'en/forest', weight: 2 },
        { source: 'en/high', target: 'en/gate', weight: 1 },
        { source: 'en/high', target: 'en/issue', weight: 2 },
        { source: 'en/high', target: 'en/plant', weight: 2 },
        { source: 'en/high', target: 'en/art', weight: 5 },
        { source: 'en/high', target: 'en/woodgrange', weight: 3 },
        { source: 'en/high', target: 'en/include', weight: 1 },
        { source: 'en/high', target: 'en/business', weight: 5 },
        { source: 'en/high', target: 'en/activity', weight: 2 },
        { source: 'en/high', target: 'en/good', weight: 2 },
        { source: 'en/high', target: 'en/improve', weight: 4 },
        { source: 'en/high', target: 'en/people', weight: 1 },
        { source: 'en/high', target: 'en/borough', weight: 3 },
        { source: 'en/high', target: 'en/newham', weight: 4 },
        { source: 'en/high', target: 'en/green', weight: 5 },
        { source: 'en/high', target: 'en/resident', weight: 1 },
        { source: 'en/high', target: 'en/public', weight: 2 },
        { source: 'en/high', target: 'en/walk', weight: 2 },
        { source: 'en/high', target: 'en/look', weight: 5 },
        { source: 'en/high', target: 'en/feel', weight: 3 },
        { source: 'en/high', target: 'en/fly', weight: 1 },
        { source: 'en/high', target: 'en/help', weight: 5 },
        { source: 'en/high', target: 'en/environment', weight: 2 },
        { source: 'en/high', target: 'en/market', weight: 2 },
        { source: 'en/high', target: 'en/youth', weight: 2 },
        { source: 'en/high', target: 'en/tree', weight: 3 },
        { source: 'en/high', target: 'en/great', weight: 1 },
        { source: 'en/high', target: 'en/new', weight: 5 },
        { source: 'en/high', target: 'en/use', weight: 3 },
        { source: 'en/high', target: 'en/outdoor', weight: 2 },
        { source: 'en/high', target: 'en/work', weight: 3 },
        { source: 'en/high', target: 'en/diversity', weight: 5 },
        { source: 'en/street', target: 'en/forest', weight: 1 },
        { source: 'en/street', target: 'en/art', weight: 1 },
        { source: 'en/street', target: 'en/market', weight: 4 },
        { source: 'en/street', target: 'en/food', weight: 6 },
        { source: 'en/street', target: 'en/environment', weight: 6 },
        { source: 'en/street', target: 'en/issue', weight: 3 },
        { source: 'en/street', target: 'en/include', weight: 3 },
        { source: 'en/street', target: 'en/area', weight: 1 },
        { source: 'en/street', target: 'en/green', weight: 6 },
        { source: 'en/street', target: 'en/feel', weight: 1 },
        { source: 'en/street', target: 'en/school', weight: 1 },
        { source: 'en/street', target: 'en/place', weight: 1 },
        { source: 'en/street', target: 'en/business', weight: 4 },
        { source: 'en/street', target: 'en/child', weight: 3 },
        { source: 'en/street', target: 'en/play', weight: 5 },
        { source: 'en/street', target: 'en/pavement', weight: 3 },
        { source: 'en/street', target: 'en/people', weight: 3 },
        { source: 'en/street', target: 'en/look', weight: 1 },
        { source: 'en/street', target: 'en/improve', weight: 7 },
        { source: 'en/street', target: 'en/shop', weight: 3 },
        { source: 'en/street', target: 'en/litter', weight: 2 },
        { source: 'en/street', target: 'en/resident', weight: 10 },
        { source: 'en/street', target: 'en/gate', weight: 5 },
        { source: 'en/street', target: 'en/borough', weight: 2 },
        { source: 'en/street', target: 'en/diversity', weight: 4 },
        { source: 'en/street', target: 'en/walk', weight: 4 },
        { source: 'en/street', target: 'en/reduce', weight: 6 },
        { source: 'en/street', target: 'en/woodgrange', weight: 2 },
        { source: 'en/street', target: 'en/safe', weight: 7 },
        { source: 'en/street', target: 'en/way', weight: 1 },
        { source: 'en/street', target: 'en/young', weight: 1 },
        { source: 'en/street', target: 'en/great', weight: 2 },
        { source: 'en/street', target: 'en/public', weight: 4 },
        { source: 'en/street', target: 'en/project', weight: 1 },
        { source: 'en/street', target: 'en/activity', weight: 4 },
        { source: 'en/street', target: 'en/waste', weight: 1 },
        { source: 'en/street', target: 'en/fly', weight: 4 },
        { source: 'en/street', target: 'en/provide', weight: 3 },
        { source: 'en/street', target: 'en/help', weight: 2 },
        { source: 'en/street', target: 'en/youth', weight: 1 },
        { source: 'en/street', target: 'en/tree', weight: 3 },
        { source: 'en/street', target: 'en/set', weight: 1 },
        { source: 'en/street', target: 'en/new', weight: 2 },
        { source: 'en/street', target: 'en/outdoor', weight: 1 },
        { source: 'en/street', target: 'en/benefit', weight: 1 },
        { source: 'en/street', target: 'en/work', weight: 2 },
        { source: 'en/shop', target: 'en/litter', weight: 3 },
        { source: 'en/shop', target: 'en/use', weight: 3 },
        { source: 'en/shop', target: 'en/business', weight: 3 },
        { source: 'en/shop', target: 'en/help', weight: 3 },
        { source: 'en/shop', target: 'en/school', weight: 1 },
        { source: 'en/shop', target: 'en/include', weight: 1 },
        { source: 'en/shop', target: 'en/improve', weight: 1 },
        { source: 'en/shop', target: 'en/people', weight: 2 },
        { source: 'en/shop', target: 'en/market', weight: 2 },
        { source: 'en/shop', target: 'en/centre', weight: 1 },
        { source: 'en/litter', target: 'en/fly', weight: 2 },
        { source: 'en/litter', target: 'en/pavement', weight: 3 },
        { source: 'en/litter', target: 'en/improve', weight: 4 },
        { source: 'en/litter', target: 'en/waste', weight: 3 },
        { source: 'en/litter', target: 'en/help', weight: 4 },
        { source: 'en/litter', target: 'en/safe', weight: 1 },
        { source: 'en/litter', target: 'en/people', weight: 1 },
        { source: 'en/litter', target: 'en/business', weight: 2 },
        { source: 'en/litter', target: 'en/place', weight: 1 },
        { source: 'en/litter', target: 'en/project', weight: 2 },
        { source: 'en/litter', target: 'en/reduce', weight: 4 },
        { source: 'en/litter', target: 'en/provide', weight: 2 },
        { source: 'en/litter', target: 'en/school', weight: 1 },
        { source: 'en/litter', target: 'en/use', weight: 1 },
        { source: 'en/litter', target: 'en/include', weight: 1 },
        { source: 'en/activity', target: 'en/environment', weight: 3 },
        { source: 'en/activity', target: 'en/people', weight: 1 },
        { source: 'en/activity', target: 'en/place', weight: 4 },
        { source: 'en/activity', target: 'en/etc', weight: 3 },
        { source: 'en/activity', target: 'en/help', weight: 4 },
        { source: 'en/activity', target: 'en/young', weight: 1 },
        { source: 'en/activity', target: 'en/improve', weight: 2 },
        { source: 'en/activity', target: 'en/child', weight: 5 },
        { source: 'en/activity', target: 'en/year', weight: 1 },
        { source: 'en/activity', target: 'en/youth', weight: 3 },
        { source: 'en/activity', target: 'en/tree', weight: 2 },
        { source: 'en/activity', target: 'en/plant', weight: 1 },
        { source: 'en/activity', target: 'en/art', weight: 3 },
        { source: 'en/activity', target: 'en/project', weight: 2 },
        { source: 'en/activity', target: 'en/mental', weight: 1 },
        { source: 'en/activity', target: 'en/health', weight: 7 },
        { source: 'en/activity', target: 'en/area', weight: 1 },
        { source: 'en/activity', target: 'en/provide', weight: 7 },
        { source: 'en/activity', target: 'en/resident', weight: 4 },
        { source: 'en/activity', target: 'en/walk', weight: 1 },
        { source: 'en/activity', target: 'en/good', weight: 1 },
        { source: 'en/activity', target: 'en/newham', weight: 1 },
        { source: 'en/activity', target: 'en/safe', weight: 1 },
        { source: 'en/activity', target: 'en/public', weight: 1 },
        { source: 'en/activity', target: 'en/look', weight: 2 },
        { source: 'en/activity', target: 'en/centre', weight: 1 },
        { source: 'en/activity', target: 'en/age', weight: 2 },
        { source: 'en/activity', target: 'en/outdoor', weight: 8 },
        { source: 'en/activity', target: 'en/play', weight: 3 },
        { source: 'en/activity', target: 'en/include', weight: 3 },
        { source: 'en/forest', target: 'en/gate', weight: 7 },
        { source: 'en/forest', target: 'en/school', weight: 4 },
        { source: 'en/forest', target: 'en/improve', weight: 3 },
        { source: 'en/forest', target: 'en/child', weight: 1 },
        { source: 'en/forest', target: 'en/youth', weight: 2 },
        { source: 'en/forest', target: 'en/art', weight: 6 },
        { source: 'en/forest', target: 'en/project', weight: 9 },
        { source: 'en/forest', target: 'en/walk', weight: 3 },
        { source: 'en/forest', target: 'en/garden', weight: 1 },
        { source: 'en/forest', target: 'en/borough', weight: 3 },
        { source: 'en/forest', target: 'en/newham', weight: 3 },
        { source: 'en/forest', target: 'en/family', weight: 3 },
        { source: 'en/forest', target: 'en/provide', weight: 3 },
        { source: 'en/forest', target: 'en/resident', weight: 6 },
        { source: 'en/forest', target: 'en/great', weight: 1 },
        { source: 'en/forest', target: 'en/area', weight: 5 },
        { source: 'en/forest', target: 'en/place', weight: 3 },
        { source: 'en/forest', target: 'en/help', weight: 1 },
        { source: 'en/forest', target: 'en/people', weight: 4 },
        { source: 'en/forest', target: 'en/age', weight: 1 },
        { source: 'en/forest', target: 'en/safe', weight: 5 },
        { source: 'en/forest', target: 'en/green', weight: 9 },
        { source: 'en/forest', target: 'en/public', weight: 2 },
        { source: 'en/forest', target: 'en/feel', weight: 3 },
        { source: 'en/forest', target: 'en/business', weight: 1 },
        { source: 'en/forest', target: 'en/trail', weight: 3 },
        { source: 'en/forest', target: 'en/wide', weight: 3 },
        { source: 'en/forest', target: 'en/plant', weight: 3 },
        { source: 'en/forest', target: 'en/environment', weight: 3 },
        { source: 'en/forest', target: 'en/market', weight: 2 },
        { source: 'en/forest', target: 'en/tree', weight: 3 },
        { source: 'en/forest', target: 'en/centre', weight: 3 },
        { source: 'en/forest', target: 'en/year', weight: 4 },
        { source: 'en/forest', target: 'en/set', weight: 2 },
        { source: 'en/forest', target: 'en/new', weight: 1 },
        { source: 'en/forest', target: 'en/use', weight: 1 },
        { source: 'en/forest', target: 'en/woodgrange', weight: 2 },
        { source: 'en/forest', target: 'en/play', weight: 3 },
        { source: 'en/forest', target: 'en/way', weight: 1 },
        { source: 'en/forest', target: 'en/diversity', weight: 3 },
        { source: 'en/forest', target: 'en/include', weight: 3 },
        { source: 'en/gate', target: 'en/improve', weight: 3 },
        { source: 'en/gate', target: 'en/youth', weight: 1 },
        { source: 'en/gate', target: 'en/borough', weight: 5 },
        { source: 'en/gate', target: 'en/area', weight: 3 },
        { source: 'en/gate', target: 'en/family', weight: 3 },
        { source: 'en/gate', target: 'en/newham', weight: 2 },
        { source: 'en/gate', target: 'en/resident', weight: 5 },
        { source: 'en/gate', target: 'en/great', weight: 4 },
        { source: 'en/gate', target: 'en/people', weight: 2 },
        { source: 'en/gate', target: 'en/child', weight: 3 },
        { source: 'en/gate', target: 'en/young', weight: 2 },
        { source: 'en/gate', target: 'en/market', weight: 1 },
        { source: 'en/gate', target: 'en/project', weight: 5 },
        { source: 'en/gate', target: 'en/walk', weight: 2 },
        { source: 'en/gate', target: 'en/place', weight: 2 },
        { source: 'en/gate', target: 'en/garden', weight: 10 },
        { source: 'en/gate', target: 'en/art', weight: 1 },
        { source: 'en/gate', target: 'en/provide', weight: 2 },
        { source: 'en/gate', target: 'en/safe', weight: 2 },
        { source: 'en/gate', target: 'en/age', weight: 4 },
        { source: 'en/gate', target: 'en/school', weight: 4 },
        { source: 'en/gate', target: 'en/help', weight: 2 },
        { source: 'en/gate', target: 'en/green', weight: 3 },
        { source: 'en/gate', target: 'en/feel', weight: 1 },
        { source: 'en/gate', target: 'en/trail', weight: 1 },
        { source: 'en/gate', target: 'en/wide', weight: 2 },
        { source: 'en/gate', target: 'en/plant', weight: 2 },
        { source: 'en/gate', target: 'en/environment', weight: 2 },
        { source: 'en/gate', target: 'en/tree', weight: 1 },
        { source: 'en/gate', target: 'en/centre', weight: 1 },
        { source: 'en/gate', target: 'en/year', weight: 2 },
        { source: 'en/gate', target: 'en/set', weight: 1 },
        { source: 'en/gate', target: 'en/play', weight: 1 },
        { source: 'en/gate', target: 'en/diversity', weight: 2 },
        { source: 'en/improve', target: 'en/look', weight: 3 },
        { source: 'en/improve', target: 'en/environment', weight: 14 },
        { source: 'en/improve', target: 'en/resident', weight: 4 },
        { source: 'en/improve', target: 'en/area', weight: 6 },
        { source: 'en/improve', target: 'en/way', weight: 3 },
        { source: 'en/improve', target: 'en/green', weight: 4 },
        { source: 'en/improve', target: 'en/newham', weight: 3 },
        { source: 'en/improve', target: 'en/child', weight: 1 },
        { source: 'en/improve', target: 'en/public', weight: 6 },
        { source: 'en/improve', target: 'en/mental', weight: 5 },
        { source: 'en/improve', target: 'en/outdoor', weight: 3 },
        { source: 'en/improve', target: 'en/health', weight: 3 },
        { source: 'en/improve', target: 'en/people', weight: 6 },
        { source: 'en/improve', target: 'en/feel', weight: 8 },
        { source: 'en/improve', target: 'en/young', weight: 3 },
        { source: 'en/improve', target: 'en/woodgrange', weight: 1 },
        { source: 'en/improve', target: 'en/reduce', weight: 2 },
        { source: 'en/improve', target: 'en/play', weight: 2 },
        { source: 'en/improve', target: 'en/diversity', weight: 1 },
        { source: 'en/improve', target: 'en/family', weight: 5 },
        { source: 'en/improve', target: 'en/benefit', weight: 1 },
        { source: 'en/improve', target: 'en/etc', weight: 2 },
        { source: 'en/improve', target: 'en/borough', weight: 2 },
        { source: 'en/improve', target: 'en/safe', weight: 1 },
        { source: 'en/improve', target: 'en/project', weight: 7 },
        { source: 'en/improve', target: 'en/waste', weight: 2 },
        { source: 'en/improve', target: 'en/plant', weight: 3 },
        { source: 'en/improve', target: 'en/help', weight: 4 },
        { source: 'en/improve', target: 'en/tree', weight: 1 },
        { source: 'en/improve', target: 'en/great', weight: 2 },
        { source: 'en/improve', target: 'en/year', weight: 1 },
        { source: 'en/improve', target: 'en/use', weight: 2 },
        { source: 'en/improve', target: 'en/work', weight: 3 },
        { source: 'en/people', target: 'en/family', weight: 6 },
        { source: 'en/people', target: 'en/etc', weight: 4 },
        { source: 'en/people', target: 'en/look', weight: 1 },
        { source: 'en/people', target: 'en/set', weight: 3 },
        { source: 'en/people', target: 'en/age', weight: 3 },
        { source: 'en/people', target: 'en/mental', weight: 5 },
        { source: 'en/people', target: 'en/project', weight: 5 },
        { source: 'en/people', target: 'en/fly', weight: 3 },
        { source: 'en/people', target: 'en/wide', weight: 3 },
        { source: 'en/people', target: 'en/year', weight: 3 },
        { source: 'en/people', target: 'en/area', weight: 1 },
        { source: 'en/people', target: 'en/feel', weight: 1 },
        { source: 'en/people', target: 'en/youth', weight: 2 },
        { source: 'en/people', target: 'en/help', weight: 4 },
        { source: 'en/people', target: 'en/newham', weight: 2 },
        { source: 'en/people', target: 'en/walk', weight: 4 },
        { source: 'en/people', target: 'en/child', weight: 5 },
        { source: 'en/people', target: 'en/borough', weight: 5 },
        { source: 'en/people', target: 'en/art', weight: 2 },
        { source: 'en/people', target: 'en/safe', weight: 3 },
        { source: 'en/people', target: 'en/tree', weight: 4 },
        { source: 'en/people', target: 'en/provide', weight: 4 },
        { source: 'en/people', target: 'en/health', weight: 6 },
        { source: 'en/people', target: 'en/outdoor', weight: 5 },
        { source: 'en/people', target: 'en/benefit', weight: 6 },
        { source: 'en/people', target: 'en/pavement', weight: 3 },
        { source: 'en/people', target: 'en/centre', weight: 1 },
        { source: 'en/people', target: 'en/way', weight: 5 },
        { source: 'en/people', target: 'en/woodgrange', weight: 1 },
        { source: 'en/people', target: 'en/use', weight: 1 },
        { source: 'en/people', target: 'en/new', weight: 5 },
        { source: 'en/people', target: 'en/green', weight: 2 },
        { source: 'en/people', target: 'en/issue', weight: 4 },
        { source: 'en/people', target: 'en/resident', weight: 3 },
        { source: 'en/people', target: 'en/reduce', weight: 2 },
        { source: 'en/people', target: 'en/environment', weight: 3 },
        { source: 'en/people', target: 'en/place', weight: 3 },
        { source: 'en/people', target: 'en/food', weight: 2 },
        { source: 'en/people', target: 'en/public', weight: 2 },
        { source: 'en/people', target: 'en/business', weight: 3 },
        { source: 'en/people', target: 'en/trail', weight: 2 },
        { source: 'en/people', target: 'en/school', weight: 3 },
        { source: 'en/people', target: 'en/young', weight: 5 },
        { source: 'en/people', target: 'en/market', weight: 3 },
        { source: 'en/people', target: 'en/great', weight: 3 },
        { source: 'en/people', target: 'en/work', weight: 7 },
        { source: 'en/people', target: 'en/good', weight: 2 },
        { source: 'en/borough', target: 'en/newham', weight: 5 },
        { source: 'en/borough', target: 'en/provide', weight: 3 },
        { source: 'en/borough', target: 'en/look', weight: 2 },
        { source: 'en/borough', target: 'en/youth', weight: 3 },
        { source: 'en/borough', target: 'en/wide', weight: 3 },
        { source: 'en/borough', target: 'en/play', weight: 3 },
        { source: 'en/borough', target: 'en/area', weight: 5 },
        { source: 'en/borough', target: 'en/include', weight: 2 },
        { source: 'en/borough', target: 'en/centre', weight: 1 },
        { source: 'en/borough', target: 'en/resident', weight: 3 },
        { source: 'en/borough', target: 'en/year', weight: 1 },
        { source: 'en/borough', target: 'en/good', weight: 1 },
        { source: 'en/borough', target: 'en/help', weight: 1 },
        { source: 'en/borough', target: 'en/diversity', weight: 2 },
        { source: 'en/borough', target: 'en/waste', weight: 1 },
        { source: 'en/borough', target: 'en/environment', weight: 1 },
        { source: 'en/borough', target: 'en/issue', weight: 3 },
        { source: 'en/borough', target: 'en/young', weight: 4 },
        { source: 'en/newham', target: 'en/youth', weight: 3 },
        { source: 'en/newham', target: 'en/young', weight: 3 },
        { source: 'en/newham', target: 'en/environment', weight: 2 },
        { source: 'en/newham', target: 'en/resident', weight: 6 },
        { source: 'en/newham', target: 'en/place', weight: 4 },
        { source: 'en/newham', target: 'en/safe', weight: 4 },
        { source: 'en/newham', target: 'en/work', weight: 2 },
        { source: 'en/newham', target: 'en/child', weight: 1 },
        { source: 'en/newham', target: 'en/mental', weight: 1 },
        { source: 'en/newham', target: 'en/benefit', weight: 1 },
        { source: 'en/newham', target: 'en/play', weight: 1 },
        { source: 'en/newham', target: 'en/public', weight: 1 },
        { source: 'en/newham', target: 'en/diversity', weight: 1 },
        { source: 'en/newham', target: 'en/help', weight: 2 },
        { source: 'en/newham', target: 'en/project', weight: 3 },
        { source: 'en/newham', target: 'en/fly', weight: 1 },
        { source: 'en/newham', target: 'en/provide', weight: 2 },
        { source: 'en/newham', target: 'en/issue', weight: 3 },
        { source: 'en/newham', target: 'en/great', weight: 4 },
        { source: 'en/newham', target: 'en/year', weight: 2 },
        { source: 'en/newham', target: 'en/set', weight: 4 },
        { source: 'en/newham', target: 'en/way', weight: 5 },
        { source: 'en/area', target: 'en/look', weight: 1 },
        { source: 'en/area', target: 'en/age', weight: 3 },
        { source: 'en/area', target: 'en/resident', weight: 2 },
        { source: 'en/area', target: 'en/art', weight: 3 },
        { source: 'en/area', target: 'en/benefit', weight: 5 },
        { source: 'en/area', target: 'en/year', weight: 3 },
        { source: 'en/area', target: 'en/provide', weight: 2 },
        { source: 'en/area', target: 'en/work', weight: 5 },
        { source: 'en/area', target: 'en/play', weight: 4 },
        { source: 'en/area', target: 'en/youth', weight: 3 },
        { source: 'en/area', target: 'en/safe', weight: 3 },
        { source: 'en/area', target: 'en/feel', weight: 7 },
        { source: 'en/area', target: 'en/way', weight: 1 },
        { source: 'en/area', target: 'en/help', weight: 1 },
        { source: 'en/area', target: 'en/young', weight: 3 },
        { source: 'en/area', target: 'en/great', weight: 3 },
        { source: 'en/area', target: 'en/fly', weight: 2 },
        { source: 'en/area', target: 'en/use', weight: 5 },
        { source: 'en/area', target: 'en/new', weight: 2 },
        { source: 'en/area', target: 'en/mental', weight: 2 },
        { source: 'en/area', target: 'en/green', weight: 4 },
        { source: 'en/area', target: 'en/place', weight: 4 },
        { source: 'en/area', target: 'en/project', weight: 6 },
        { source: 'en/area', target: 'en/wide', weight: 1 },
        { source: 'en/area', target: 'en/plant', weight: 4 },
        { source: 'en/area', target: 'en/garden', weight: 5 },
        { source: 'en/area', target: 'en/environment', weight: 3 },
        { source: 'en/area', target: 'en/etc', weight: 2 },
        { source: 'en/area', target: 'en/family', weight: 5 },
        { source: 'en/area', target: 'en/tree', weight: 4 },
        { source: 'en/area', target: 'en/outdoor', weight: 2 },
        { source: 'en/area', target: 'en/diversity', weight: 3 },
        { source: 'en/area', target: 'en/include', weight: 1 },
        { source: 'en/area', target: 'en/good', weight: 4 },
        { source: 'en/safe', target: 'en/green', weight: 5 },
        { source: 'en/safe', target: 'en/place', weight: 3 },
        { source: 'en/safe', target: 'en/family', weight: 1 },
        { source: 'en/safe', target: 'en/walk', weight: 3 },
        { source: 'en/safe', target: 'en/use', weight: 3 },
        { source: 'en/safe', target: 'en/work', weight: 1 },
        { source: 'en/safe', target: 'en/new', weight: 2 },
        { source: 'en/safe', target: 'en/resident', weight: 1 },
        { source: 'en/safe', target: 'en/young', weight: 1 },
        { source: 'en/safe', target: 'en/play', weight: 2 },
        { source: 'en/safe', target: 'en/outdoor', weight: 2 },
        { source: 'en/safe', target: 'en/public', weight: 4 },
        { source: 'en/safe', target: 'en/feel', weight: 5 },
        { source: 'en/safe', target: 'en/provide', weight: 2 },
        { source: 'en/safe', target: 'en/plant', weight: 2 },
        { source: 'en/safe', target: 'en/help', weight: 2 },
        { source: 'en/safe', target: 'en/tree', weight: 3 },
        { source: 'en/safe', target: 'en/benefit', weight: 2 },
        { source: 'en/green', target: 'en/work', weight: 3 },
        { source: 'en/green', target: 'en/waste', weight: 2 },
        { source: 'en/green', target: 'en/tree', weight: 3 },
        { source: 'en/green', target: 'en/outdoor', weight: 4 },
        { source: 'en/green', target: 'en/etc', weight: 1 },
        { source: 'en/green', target: 'en/young', weight: 1 },
        { source: 'en/green', target: 'en/environment', weight: 1 },
        { source: 'en/green', target: 'en/place', weight: 2 },
        { source: 'en/green', target: 'en/resident', weight: 2 },
        { source: 'en/green', target: 'en/plant', weight: 3 },
        { source: 'en/green', target: 'en/art', weight: 1 },
        { source: 'en/green', target: 'en/good', weight: 1 },
        { source: 'en/green', target: 'en/benefit', weight: 2 },
        { source: 'en/green', target: 'en/play', weight: 2 },
        { source: 'en/green', target: 'en/public', weight: 3 },
        { source: 'en/green', target: 'en/walk', weight: 2 },
        { source: 'en/green', target: 'en/provide', weight: 2 },
        { source: 'en/green', target: 'en/great', weight: 3 },
        { source: 'en/green', target: 'en/include', weight: 5 },
        { source: 'en/resident', target: 'en/benefit', weight: 5 },
        { source: 'en/resident', target: 'en/art', weight: 3 },
        { source: 'en/resident', target: 'en/work', weight: 3 },
        { source: 'en/resident', target: 'en/provide', weight: 5 },
        { source: 'en/resident', target: 'en/family', weight: 3 },
        { source: 'en/resident', target: 'en/walk', weight: 3 },
        { source: 'en/resident', target: 'en/great', weight: 1 },
        {
          source: 'en/resident',
          target: 'en/year',
          weight: 4,
        },
        { source: 'en/resident', target: 'en/help', weight: 5 },
        { source: 'en/resident', target: 'en/public', weight: 5 },
        { source: 'en/resident', target: 'en/school', weight: 3 },
        { source: 'en/resident', target: 'en/new', weight: 3 },
        { source: 'en/resident', target: 'en/wide', weight: 2 },
        { source: 'en/resident', target: 'en/play', weight: 1 },
        { source: 'en/resident', target: 'en/set', weight: 5 },
        { source: 'en/resident', target: 'en/garden', weight: 3 },
        { source: 'en/resident', target: 'en/reduce', weight: 4 },
        { source: 'en/resident', target: 'en/plant', weight: 2 },
        { source: 'en/resident', target: 'en/look', weight: 2 },
        { source: 'en/resident', target: 'en/outdoor', weight: 2 },
        { source: 'en/resident', target: 'en/environment', weight: 4 },
        { source: 'en/resident', target: 'en/project', weight: 5 },
        { source: 'en/resident', target: 'en/feel', weight: 2 },
        { source: 'en/resident', target: 'en/health', weight: 4 },
        { source: 'en/resident', target: 'en/business', weight: 3 },
        { source: 'en/resident', target: 'en/child', weight: 3 },
        { source: 'en/resident', target: 'en/market', weight: 2 },
        { source: 'en/resident', target: 'en/pavement', weight: 1 },
        { source: 'en/resident', target: 'en/centre', weight: 3 },
        { source: 'en/resident', target: 'en/use', weight: 4 },
        { source: 'en/resident', target: 'en/mental', weight: 2 },
        { source: 'en/resident', target: 'en/way', weight: 1 },
        { source: 'en/resident', target: 'en/include', weight: 2 },
        { source: 'en/place', target: 'en/child', weight: 3 },
        { source: 'en/place', target: 'en/school', weight: 2 },
        { source: 'en/place', target: 'en/great', weight: 3 },
        { source: 'en/place', target: 'en/plant', weight: 3 },
        { source: 'en/place', target: 'en/fly', weight: 2 },
        { source: 'en/place', target: 'en/work', weight: 2 },
        { source: 'en/place', target: 'en/young', weight: 1 },
        { source: 'en/place', target: 'en/use', weight: 3 },
        { source: 'en/place', target: 'en/play', weight: 2 },
        { source: 'en/place', target: 'en/walk', weight: 3 },
        { source: 'en/place', target: 'en/feel', weight: 1 },
        { source: 'en/place', target: 'en/reduce', weight: 1 },
        { source: 'en/place', target: 'en/garden', weight: 3 },
        { source: 'en/place', target: 'en/market', weight: 3 },
        { source: 'en/place', target: 'en/youth', weight: 2 },
        { source: 'en/place', target: 'en/woodgrange', weight: 4 },
        { source: 'en/place', target: 'en/benefit', weight: 1 },
        { source: 'en/place', target: 'en/good', weight: 3 },
        { source: 'en/project', target: 'en/young', weight: 1 },
        { source: 'en/project', target: 'en/benefit', weight: 3 },
        { source: 'en/project', target: 'en/youth', weight: 4 },
        { source: 'en/project', target: 'en/year', weight: 3 },
        { source: 'en/project', target: 'en/feel', weight: 3 },
        { source: 'en/project', target: 'en/great', weight: 3 },
        { source: 'en/project', target: 'en/include', weight: 1 },
        { source: 'en/project', target: 'en/child', weight: 3 },
        { source: 'en/project', target: 'en/help', weight: 1 },
        { source: 'en/project', target: 'en/use', weight: 3 },
        { source: 'en/project', target: 'en/work', weight: 5 },
        { source: 'en/project', target: 'en/food', weight: 1 },
        { source: 'en/project', target: 'en/etc', weight: 1 },
        { source: 'en/project', target: 'en/new', weight: 1 },
        { source: 'en/project', target: 'en/woodgrange', weight: 1 },
        { source: 'en/project', target: 'en/play', weight: 3 },
        { source: 'en/project', target: 'en/public', weight: 3 },
        { source: 'en/project', target: 'en/school', weight: 1 },
        { source: 'en/project', target: 'en/wide', weight: 2 },
        { source: 'en/project', target: 'en/waste', weight: 2 },
        { source: 'en/project', target: 'en/walk', weight: 5 },
        { source: 'en/project', target: 'en/health', weight: 5 },
        { source: 'en/project', target: 'en/garden', weight: 2 },
        { source: 'en/project', target: 'en/art', weight: 3 },
        { source: 'en/project', target: 'en/set', weight: 3 },
        { source: 'en/project', target: 'en/mental', weight: 1 },
        { source: 'en/project', target: 'en/age', weight: 1 },
        { source: 'en/waste', target: 'en/look', weight: 4 },
        { source: 'en/waste', target: 'en/woodgrange', weight: 1 },
        { source: 'en/waste', target: 'en/fly', weight: 3 },
        { source: 'en/waste', target: 'en/public', weight: 2 },
        { source: 'en/waste', target: 'en/walk', weight: 2 },
        { source: 'en/waste', target: 'en/issue', weight: 2 },
        { source: 'en/waste', target: 'en/etc', weight: 2 },
        { source: 'en/waste', target: 'en/garden', weight: 1 },
        { source: 'en/waste', target: 'en/business', weight: 1 },
        { source: 'en/waste', target: 'en/reduce', weight: 3 },
        { source: 'en/waste', target: 'en/great', weight: 1 },
        { source: 'en/waste', target: 'en/use', weight: 3 },
        { source: 'en/waste', target: 'en/food', weight: 3 },
        { source: 'en/waste', target: 'en/way', weight: 2 },
        { source: 'en/public', target: 'en/use', weight: 3 },
        { source: 'en/public', target: 'en/art', weight: 5 },
        { source: 'en/public', target: 'en/health', weight: 3 },
        { source: 'en/public', target: 'en/child', weight: 2 },
        { source: 'en/public', target: 'en/young', weight: 1 },
        { source: 'en/public', target: 'en/fly', weight: 1 },
        { source: 'en/public', target: 'en/reduce', weight: 2 },
        { source: 'en/public', target: 'en/wide', weight: 1 },
        { source: 'en/public', target: 'en/garden', weight: 1 },
        { source: 'en/public', target: 'en/family', weight: 4 },
        { source: 'en/public', target: 'en/look', weight: 2 },
        { source: 'en/public', target: 'en/food', weight: 1 },
        { source: 'en/public', target: 'en/way', weight: 2 },
        { source: 'en/public', target: 'en/provide', weight: 3 },
        { source: 'en/public', target: 'en/outdoor', weight: 2 },
        { source: 'en/public', target: 'en/benefit', weight: 3 },
        { source: 'en/public', target: 'en/work', weight: 3 },
        { source: 'en/public', target: 'en/diversity', weight: 1 },
        { source: 'en/public', target: 'en/include', weight: 3 },
        { source: 'en/walk', target: 'en/pavement', weight: 2 },
        { source: 'en/walk', target: 'en/feel', weight: 4 },
        { source: 'en/look', target: 'en/feel', weight: 4 },
        { source: 'en/look', target: 'en/environment', weight: 3 },
        { source: 'en/look', target: 'en/good', weight: 2 },
        { source: 'en/look', target: 'en/provide', weight: 3 },
        { source: 'en/look', target: 'en/tree', weight: 3 },
        { source: 'en/look', target: 'en/way', weight: 2 },
        { source: 'en/look', target: 'en/year', weight: 1 },
        { source: 'en/look', target: 'en/business', weight: 1 },
        { source: 'en/look', target: 'en/plant', weight: 2 },
        { source: 'en/look', target: 'en/help', weight: 3 },
        { source: 'en/look', target: 'en/young', weight: 2 },
        { source: 'en/look', target: 'en/woodgrange', weight: 2 },
        { source: 'en/feel', target: 'en/help', weight: 4 },
        { source: 'en/feel', target: 'en/work', weight: 3 },
        { source: 'en/feel', target: 'en/reduce', weight: 1 },
        { source: 'en/feel', target: 'en/family', weight: 1 },
        { source: 'en/feel', target: 'en/provide', weight: 1 },
        { source: 'en/feel', target: 'en/young', weight: 2 },
        { source: 'en/feel', target: 'en/play', weight: 1 },
        { source: 'en/feel', target: 'en/fly', weight: 2 },
        { source: 'en/feel', target: 'en/child', weight: 3 },
        { source: 'en/feel', target: 'en/benefit', weight: 2 },
        { source: 'en/feel', target: 'en/food', weight: 1 },
        { source: 'en/reduce', target: 'en/play', weight: 3 },
        { source: 'en/reduce', target: 'en/fly', weight: 2 },
        { source: 'en/reduce', target: 'en/use', weight: 1 },
        { source: 'en/reduce', target: 'en/provide', weight: 1 },
        { source: 'en/reduce', target: 'en/food', weight: 2 },
        { source: 'en/reduce', target: 'en/family', weight: 1 },
        { source: 'en/reduce', target: 'en/health', weight: 3 },
        { source: 'en/reduce', target: 'en/garden', weight: 1 },
        { source: 'en/reduce', target: 'en/help', weight: 3 },
        { source: 'en/reduce', target: 'en/environment', weight: 1 },
        { source: 'en/fly', target: 'en/set', weight: 2 },
        { source: 'en/fly', target: 'en/school', weight: 3 },
        { source: 'en/health', target: 'en/outdoor', weight: 1 },
        { source: 'en/health', target: 'en/benefit', weight: 3 },
        { source: 'en/health', target: 'en/issue', weight: 1 },
        { source: 'en/health', target: 'en/youth', weight: 2 },
        { source: 'en/health', target: 'en/mental', weight: 7 },
        { source: 'en/health', target: 'en/year', weight: 4 },
        { source: 'en/health', target: 'en/age', weight: 1 },
        { source: 'en/health', target: 'en/young', weight: 1 },
        { source: 'en/health', target: 'en/child', weight: 2 },
        { source: 'en/health', target: 'en/centre', weight: 2 },
        { source: 'en/health', target: 'en/environment', weight: 3 },
        { source: 'en/health', target: 'en/provide', weight: 3 },
        { source: 'en/health', target: 'en/help', weight: 2 },
        { source: 'en/health', target: 'en/great', weight: 2 },
        { source: 'en/business', target: 'en/market', weight: 3 },
        { source: 'en/business', target: 'en/wide', weight: 3 },
        { source: 'en/business', target: 'en/pavement', weight: 2 },
        { source: 'en/business', target: 'en/trail', weight: 5 },
        { source: 'en/business', target: 'en/diversity', weight: 1 },
        { source: 'en/business', target: 'en/etc', weight: 1 },
        { source: 'en/business', target: 'en/help', weight: 2 },
        { source: 'en/business', target: 'en/benefit', weight: 1 },
        { source: 'en/business', target: 'en/outdoor', weight: 1 },
        { source: 'en/business', target: 'en/set', weight: 1 },
        { source: 'en/business', target: 'en/new', weight: 4 },
        { source: 'en/business', target: 'en/food', weight: 3 },
        { source: 'en/business', target: 'en/include', weight: 4 },
        { source: 'en/business', target: 'en/good', weight: 2 },
        { source: 'en/trail', target: 'en/centre', weight: 4 },
        { source: 'en/trail', target: 'en/school', weight: 2 },
        { source: 'en/trail', target: 'en/way', weight: 2 },
        { source: 'en/trail', target: 'en/tree', weight: 2 },
        { source: 'en/trail', target: 'en/garden', weight: 3 },
        { source: 'en/trail', target: 'en/young', weight: 1 },
        { source: 'en/trail', target: 'en/pavement', weight: 3 },
        { source: 'en/provide', target: 'en/food', weight: 1 },
        { source: 'en/provide', target: 'en/help', weight: 1 },
        { source: 'en/provide', target: 'en/youth', weight: 3 },
        { source: 'en/provide', target: 'en/set', weight: 5 },
        { source: 'en/provide', target: 'en/environment', weight: 2 },
        { source: 'en/provide', target: 'en/year', weight: 5 },
        { source: 'en/provide', target: 'en/young', weight: 1 },
        { source: 'en/provide', target: 'en/plant', weight: 4 },
        { source: 'en/provide', target: 'en/garden', weight: 3 },
        { source: 'en/provide', target: 'en/issue', weight: 4 },
        { source: 'en/provide', target: 'en/use', weight: 2 },
        { source: 'en/provide', target: 'en/mental', weight: 1 },
        { source: 'en/provide', target: 'en/benefit', weight: 2 },
        { source: 'en/provide', target: 'en/good', weight: 2 },
        { source: 'en/wide', target: 'en/age', weight: 5 },
        { source: 'en/wide', target: 'en/diversity', weight: 2 },
        { source: 'en/wide', target: 'en/woodgrange', weight: 2 },
        { source: 'en/wide', target: 'en/market', weight: 1 },
        { source: 'en/wide', target: 'en/help', weight: 1 },
        { source: 'en/wide', target: 'en/child', weight: 1 },
        { source: 'en/wide', target: 'en/young', weight: 2 },
        { source: 'en/wide', target: 'en/use', weight: 1 },
        { source: 'en/wide', target: 'en/benefit', weight: 3 },
        { source: 'en/wide', target: 'en/good', weight: 2 },
        { source: 'en/plant', target: 'en/tree', weight: 9 },
        { source: 'en/plant', target: 'en/environment', weight: 2 },
        { source: 'en/plant', target: 'en/garden', weight: 3 },
        { source: 'en/plant', target: 'en/new', weight: 3 },
        { source: 'en/plant', target: 'en/young', weight: 2 },
        { source: 'en/plant', target: 'en/help', weight: 2 },
        { source: 'en/plant', target: 'en/diversity', weight: 1 },
        { source: 'en/plant', target: 'en/school', weight: 1 },
        { source: 'en/garden', target: 'en/child', weight: 5 },
        { source: 'en/garden', target: 'en/etc', weight: 3 },
        { source: 'en/garden', target: 'en/tree', weight: 4 },
        { source: 'en/garden', target: 'en/include', weight: 2 },
        { source: 'en/garden', target: 'en/help', weight: 1 },
        { source: 'en/garden', target: 'en/play', weight: 1 },
        { source: 'en/help', target: 'en/child', weight: 3 },
        { source: 'en/help', target: 'en/set', weight: 3 },
        { source: 'en/help', target: 'en/environment', weight: 2 },
        { source: 'en/help', target: 'en/centre', weight: 3 },
        { source: 'en/help', target: 'en/work', weight: 5 },
        { source: 'en/help', target: 'en/issue', weight: 2 },
        { source: 'en/help', target: 'en/art', weight: 2 },
        { source: 'en/help', target: 'en/way', weight: 2 },
        { source: 'en/help', target: 'en/mental', weight: 4 },
        { source: 'en/help', target: 'en/family', weight: 1 },
        { source: 'en/help', target: 'en/pavement', weight: 1 },
        { source: 'en/help', target: 'en/tree', weight: 2 },
        { source: 'en/help', target: 'en/young', weight: 2 },
        { source: 'en/help', target: 'en/youth', weight: 2 },
        { source: 'en/help', target: 'en/year', weight: 5 },
        { source: 'en/help', target: 'en/outdoor', weight: 3 },
        { source: 'en/help', target: 'en/benefit', weight: 1 },
        { source: 'en/help', target: 'en/play', weight: 1 },
        { source: 'en/environment', target: 'en/tree', weight: 3 },
        { source: 'en/environment', target: 'en/great', weight: 2 },
        { source: 'en/environment', target: 'en/market', weight: 1 },
        { source: 'en/environment', target: 'en/art', weight: 4 },
        { source: 'en/environment', target: 'en/pavement', weight: 1 },
        { source: 'en/environment', target: 'en/outdoor', weight: 2 },
        { source: 'en/environment', target: 'en/benefit', weight: 2 },
        { source: 'en/environment', target: 'en/way', weight: 1 },
        { source: 'en/environment', target: 'en/good', weight: 1 },
        { source: 'en/school', target: 'en/woodgrange', weight: 2 },
        { source: 'en/school', target: 'en/child', weight: 1 },
        { source: 'en/school', target: 'en/centre', weight: 3 },
        { source: 'en/school', target: 'en/tree', weight: 2 },
        { source: 'en/school', target: 'en/diversity', weight: 2 },
        { source: 'en/school', target: 'en/young', weight: 2 },
        { source: 'en/school', target: 'en/use', weight: 1 },
        { source: 'en/school', target: 'en/new', weight: 1 },
        { source: 'en/school', target: 'en/play', weight: 2 },
        { source: 'en/school', target: 'en/include', weight: 3 },
        { source: 'en/issue', target: 'en/youth', weight: 3 },
        { source: 'en/issue', target: 'en/etc', weight: 3 },
        { source: 'en/issue', target: 'en/food', weight: 3 },
        { source: 'en/issue', target: 'en/play', weight: 2 },
        { source: 'en/issue', target: 'en/mental', weight: 4 },
        { source: 'en/issue', target: 'en/child', weight: 1 },
        { source: 'en/issue', target: 'en/young', weight: 1 },
        { source: 'en/issue', target: 'en/centre', weight: 3 },
        { source: 'en/etc', target: 'en/new', weight: 2 },
        { source: 'en/etc', target: 'en/tree', weight: 3 },
        { source: 'en/etc', target: 'en/set', weight: 3 },
        { source: 'en/etc', target: 'en/use', weight: 2 },
        { source: 'en/etc', target: 'en/benefit', weight: 3 },
        { source: 'en/etc', target: 'en/food', weight: 3 },
        { source: 'en/child', target: 'en/young', weight: 3 },
        { source: 'en/child', target: 'en/youth', weight: 3 },
        { source: 'en/child', target: 'en/outdoor', weight: 3 },
        { source: 'en/child', target: 'en/play', weight: 3 },
        { source: 'en/child', target: 'en/family', weight: 1 },
        { source: 'en/child', target: 'en/mental', weight: 3 },
        { source: 'en/child', target: 'en/good', weight: 2 },
        { source: 'en/child', target: 'en/great', weight: 2 },
        { source: 'en/child', target: 'en/food', weight: 4 },
        { source: 'en/child', target: 'en/age', weight: 2 },
        { source: 'en/child', target: 'en/new', weight: 1 },
        { source: 'en/child', target: 'en/work', weight: 3 },
        { source: 'en/young', target: 'en/family', weight: 3 },
        { source: 'en/young', target: 'en/age', weight: 7 },
        { source: 'en/young', target: 'en/youth', weight: 4 },
        { source: 'en/young', target: 'en/set', weight: 1 },
        { source: 'en/young', target: 'en/mental', weight: 2 },
        { source: 'en/young', target: 'en/great', weight: 3 },
        { source: 'en/young', target: 'en/use', weight: 1 },
        { source: 'en/young', target: 'en/play', weight: 1 },
        { source: 'en/young', target: 'en/new', weight: 3 },
        { source: 'en/young', target: 'en/outdoor', weight: 6 },
        { source: 'en/young', target: 'en/benefit', weight: 3 },
        { source: 'en/young', target: 'en/work', weight: 6 },
        { source: 'en/family', target: 'en/benefit', weight: 3 },
        { source: 'en/family', target: 'en/food', weight: 2 },
        { source: 'en/family', target: 'en/year', weight: 2 },
        { source: 'en/family', target: 'en/play', weight: 2 },
        { source: 'en/market', target: 'en/woodgrange', weight: 4 },
        { source: 'en/market', target: 'en/include', weight: 3 },
        { source: 'en/market', target: 'en/set', weight: 3 },
        { source: 'en/market', target: 'en/food', weight: 4 },
        { source: 'en/market', target: 'en/art', weight: 3 },
        { source: 'en/market', target: 'en/use', weight: 1 },
        { source: 'en/youth', target: 'en/mental', weight: 2 },
        { source: 'en/youth', target: 'en/centre', weight: 4 },
        { source: 'en/youth', target: 'en/outdoor', weight: 1 },
        { source: 'en/youth', target: 'en/work', weight: 1 },
        { source: 'en/youth', target: 'en/art', weight: 3 },
        { source: 'en/youth', target: 'en/set', weight: 2 },
        { source: 'en/art', target: 'en/work', weight: 3 },
        { source: 'en/art', target: 'en/way', weight: 3 },
        { source: 'en/art', target: 'en/tree', weight: 1 },
        { source: 'en/art', target: 'en/woodgrange', weight: 2 },
        { source: 'en/art', target: 'en/diversity', weight: 2 },
        { source: 'en/art', target: 'en/good', weight: 1 },
        { source: 'en/art', target: 'en/age', weight: 1 },
        { source: 'en/art', target: 'en/benefit', weight: 1 },
        { source: 'en/art', target: 'en/play', weight: 1 },
        { source: 'en/art', target: 'en/food', weight: 2 },
        { source: 'en/tree', target: 'en/pavement', weight: 3 },
        { source: 'en/tree', target: 'en/woodgrange', weight: 3 },
        { source: 'en/tree', target: 'en/new', weight: 2 },
        { source: 'en/pavement', target: 'en/use', weight: 2 },
        { source: 'en/centre', target: 'en/mental', weight: 3 },
        { source: 'en/centre', target: 'en/use', weight: 5 },
        { source: 'en/centre', target: 'en/year', weight: 1 },
        { source: 'en/centre', target: 'en/work', weight: 2 },
        { source: 'en/great', target: 'en/use', weight: 6 },
        { source: 'en/great', target: 'en/way', weight: 3 },
        { source: 'en/great', target: 'en/good', weight: 3 },
        { source: 'en/great', target: 'en/food', weight: 1 },
        { source: 'en/great', target: 'en/year', weight: 3 },
        { source: 'en/great', target: 'en/new', weight: 2 },
        { source: 'en/year', target: 'en/set', weight: 3 },
        { source: 'en/year', target: 'en/new', weight: 1 },
        { source: 'en/year', target: 'en/work', weight: 3 },
        { source: 'en/set', target: 'en/food', weight: 2 },
        { source: 'en/new', target: 'en/use', weight: 3 },
        { source: 'en/new', target: 'en/outdoor', weight: 1 },
        { source: 'en/use', target: 'en/good', weight: 3 },
        { source: 'en/use', target: 'en/outdoor', weight: 1 },
        { source: 'en/use', target: 'en/way', weight: 5 },
        { source: 'en/use', target: 'en/woodgrange', weight: 2 },
        { source: 'en/use', target: 'en/play', weight: 3 },
        { source: 'en/mental', target: 'en/outdoor', weight: 1 },
        { source: 'en/mental', target: 'en/benefit', weight: 5 },
        { source: 'en/mental', target: 'en/play', weight: 1 },
        { source: 'en/mental', target: 'en/include', weight: 1 },
        { source: 'en/woodgrange', target: 'en/benefit', weight: 1 },
        { source: 'en/woodgrange', target: 'en/food', weight: 2 },
        { source: 'en/woodgrange', target: 'en/way', weight: 3 },
        { source: 'en/woodgrange', target: 'en/diversity', weight: 3 },
        { source: 'en/age', target: 'en/play', weight: 1 },
        { source: 'en/age', target: 'en/work', weight: 1 },
        { source: 'en/age', target: 'en/good', weight: 5 },
        { source: 'en/outdoor', target: 'en/play', weight: 1 },
        { source: 'en/outdoor', target: 'en/benefit', weight: 2 },
        { source: 'en/benefit', target: 'en/food', weight: 3 },
        { source: 'en/benefit', target: 'en/play', weight: 3 },
        { source: 'en/play', target: 'en/include', weight: 2 },
        { source: 'en/play', target: 'en/way', weight: 2 },
        { source: 'en/play', target: 'en/good', weight: 2 },
        { source: 'en/food', target: 'en/include', weight: 2 },
        { source: 'en/way', target: 'en/good', weight: 2 },
      ],
    },
  },
};
